#!/usr/bin/bash

# Tell this script to exit if there are any errors.
# You should have this in every custom script, to ensure that your completed
# builds actually ran successfully without any errors!
set -ouex pipefail

KERNEL_SUFFIX=""
# Find the kernel version we just installed by checking RPM database
QUALIFIED_KERNEL="$(rpm -qa | grep '^kernel-6' | grep -v headers | grep -v-devel | head -n1 | sed 's/^kernel-//')"
/usr/bin/dracut --no-hostonly --kver "$QUALIFIED_KERNEL" --reproducible --zstd -v --add ostree -f "/usr/lib/modules/$QUALIFIED_KERNEL/initramfs.img"

chmod 0600 /usr/lib/modules/"$QUALIFIED_KERNEL"/initramfs.img
