#!/usr/bin/bash

set -eoux pipefail

# Remove kernel packages
dnf5 -y remove --no-autoremove kernel kernel-core kernel-modules kernel-modules-core kernel-modules-extra

# Install kernel from OCI container
shopt -s nullglob
dnf5 -y install \
    /rpms/kernel/*.rpm

dnf5 versionlock add kernel kernel-devel kernel-devel-matched kernel-core kernel-modules kernel-modules-core kernel-modules-extra kernel-uki-virt

# Install additional kmods
shopt -s nullglob
dnf5 -y install \
    /rpms/*kvmfr*.rpm \
    /rpms/*xone*.rpm \
    /rpms/*openrazer*.rpm \
    /rpms/*v4l2loopback*.rpm \
    /rpms/*wl*.rpm

dnf5 -y copr enable bieszczaders/kernel-cachyos-addons && \
dnf5 -y install \
    scx-scheds && \
dnf5 -y copr disable bieszczaders/kernel-cachyos-addons
