#!/usr/bin/bash

set -eoux pipefail

# Disable 99-uki-uefi-setup.install to avoid EFI partition check
mv /usr/lib/kernel/install.d/99-uki-uefi-setup.install /usr/lib/kernel/install.d/99-uki-uefi-setup.install.bak || true
echo '#!/bin/sh\nexit 0' > /usr/lib/kernel/install.d/99-uki-uefi-setup.install
chmod +x /usr/lib/kernel/install.d/99-uki-uefi-setup.install

dnf5 -y remove --no-autoremove kernel kernel-core kernel-modules kernel-modules-core kernel-modules-extra

# Restore original 99-uki-uefi-setup.install
mv /usr/lib/kernel/install.d/99-uki-uefi-setup.install.bak /usr/lib/kernel/install.d/99-uki-uefi-setup.install || true

dnf5 -y install \
    /tmp/kernel-rpms/kernel-[0-9]*.rpm \
    /tmp/kernel-rpms/kernel-core-*.rpm \
    /tmp/kernel-rpms/kernel-modules-*.rpm \
    /tmp/kernel-rpms/kernel-devel-*.rpm

dnf5 versionlock add kernel kernel-devel kernel-devel-matched kernel-core kernel-modules kernel-modules-core kernel-modules-extra kernel-uki-virt

shopt -s nullglob
dnf5 -y install \
    /tmp/akmods-rpms/kmods/*xone*.rpm \
    /tmp/akmods-rpms/kmods/*openrazer*.rpm \
    /tmp/akmods-rpms/kmods/*v4l2loopback*.rpm \
    /tmp/akmods-rpms/kmods/*wl*.rpm \
    /tmp/akmods-extra-rpms/kmods/*nct6687*.rpm \
    /tmp/akmods-extra-rpms/kmods/*gcadapter_oc*.rpm \
    /tmp/akmods-extra-rpms/kmods/*zenergy*.rpm \
    /tmp/akmods-extra-rpms/kmods/*bmi260*.rpm \
    /tmp/akmods-extra-rpms/kmods/*ryzen-smu*.rpm \
    /tmp/akmods-extra-rpms/kmods/*evdi*.rpm

dnf5 -y copr enable bieszczaders/kernel-cachyos-addons && \
dnf5 -y install \
    scx-scheds && \
dnf5 -y copr disable bieszczaders/kernel-cachyos-addons
