#!/usr/bin/bash

set -eoux pipefail

# Installation Mesa Terra pour variantes stables
# Basé sur l'approche Bazzite - le swap de mesa-filesystem tire automatiquement
# tous les autres packages Mesa depuis terra-mesa

# Swap Mesa filesystem avec la version Terra
dnf5 -y swap --repo=terra-mesa mesa-filesystem mesa-filesystem

# Verrouiller les versions Mesa pour éviter les downgrades
dnf5 versionlock add \
    mesa-dri-drivers \
    mesa-filesystem \
    mesa-libEGL \
    mesa-libGL \
    mesa-libgbm \
    mesa-va-drivers \
    mesa-vulkan-drivers