#!/usr/bin/bash

# Installation Mesa Terra pour les images test (multilib)
# Version multilib avec support i686 complet
# Terra fc44 : les fichiers LICENSE.dependencies sont nommés par arch (.i386 / .x86_64),
# donc pas de conflit de fichier entre i686 et x86_64

set -eoux pipefail

# Swap Mesa filesystem avec la version Terra
dnf5 -y swap --from-repo=terra-mesa --enable-repo=terra-mesa mesa-filesystem mesa-filesystem

# Installer les paquets Mesa x86_64
dnf5 -y --enable-repo=terra-mesa install \
    mesa-dri-drivers \
    mesa-libEGL \
    mesa-libGL \
    mesa-libgbm \
    mesa-vulkan-drivers

# Installer les paquets Mesa i686
dnf5 -y --enable-repo=terra-mesa install \
    mesa-dri-drivers.i686 \
    mesa-libEGL.i686 \
    mesa-libGL.i686 \
    mesa-libgbm.i686 \
    mesa-vulkan-drivers.i686

# Verrouiller les versions Mesa pour éviter les downgrades
dnf5 versionlock add \
    mesa-dri-drivers \
    mesa-filesystem \
    mesa-libEGL \
    mesa-libGL \
    mesa-libgbm \
    mesa-vulkan-drivers
