#!/usr/bin/env bash

# Tell this script to exit if there are any errors.
# You should have this in every custom script, to ensure that your completed
# builds actually ran successfully without any errors!
set -ouex pipefail

dnf5 -y remove nvidia-gpu-firmware

# Install NVIDIA drivers from OCI container
shopt -s nullglob
dnf5 -y install \
    $(find "/rpms/nvidia" -type f ! -name "*debuginfo*" ! -name "*debugsource*")

rm -f /usr/share/vulkan/icd.d/nouveau_icd.*.json
ln -s libnvidia-ml.so.1 /usr/lib64/libnvidia-ml.so
