monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.usb.*"
      },
      {
        node.name = "~alsa_input.usb.*"
      }
    ]
    actions = {
      update-props = {
        node.latency      = "1536/48000"
        api.alsa.disable-batch = true
      }
    }
  }
]
