type: containerfile
snippets:
  - COPY --from=ghcr.io/ublue-os/akmods-nvidia:fsync-40  /rpms /tmp/akmods-rpms
  - COPY --from=ghcr.io/ublue-os/fsync-kernel:6.9.12-203.fsync.fc40.x86_64 /tmp/rpms/ /tmp/kernel-rpms
  - RUN curl -Lo /usr/lib/sysctl.d/99-bore-scheduler.conf https://github.com/CachyOS/CachyOS-Settings/raw/master/usr/lib/sysctl.d/99-bore-scheduler.conf
