#!/usr/bin/bash

# Arrêter le script à la moindre erreur
set -e

# Lancer une barre de progression "busy" (sans pourcentage)
dbusRef=$(kdialog --title "Mise à jour de Archgab" --progressbar "Mise à jour de Archgab en cours..." 0)
# Désactivation du bouton "Annuler"
qdbus $dbusRef showCancelButton false

# Fonction pour gérer les erreurs
on_error() {
    qdbus $dbusRef close
    kdialog --msgbox "Erreur de la mise à jour Archgab"
    exit 1
}

# Attraper les erreurs avec trap
trap 'on_error' ERR

# Mettre à jour le texte affiché
qdbus $dbusRef setLabelText "Arrêt de tous les conteneurs Podman..."
podman kill --all

# Mettre à jour le texte
qdbus $dbusRef setLabelText "Suppression de l'ancienne instance Archgab..."
distrobox-rm -f archgab

# Mettre à jour le texte
qdbus $dbusRef setLabelText "Création de la nouvelle instance Archgab..."
if lspci | grep -i nvidia > /dev/null; then
    distrobox-create --pull latest --name archgab --nvidia --image ghcr.io/elgabo86/archgab:latest
else
    distrobox-create --pull latest --name archgab --image ghcr.io/elgabo86/archgab:latest
fi

# Mettre à jour le texte
qdbus $dbusRef setLabelText "Exportation des binaires dans Archgab..."
distrobox-enter -n archgab -- bash -c 'distrobox-export --bin /usr/bin/tochd;distrobox-export --bin /usr/bin/xdvdfs'

# Purger les images Podman sans tag
podman image prune -f

# Fermer la barre de progression
qdbus $dbusRef close

kdialog --msgbox "Archgab est à jour"
