#!/usr/bin/bash

# Arrêter le script à la moindre erreur
set -e

# Lancer une barre de progression "busy" (sans pourcentage)
dbusRef=$(kdialog --title "Mise à jour de Gablue" --progressbar "Tentative de mise à jour du système..." 0)
# Désactivation du bouton "Annuler"
qdbus $dbusRef showCancelButton false

# Fonction pour gérer les erreurs
on_error() {
    qdbus $dbusRef close
    kdialog --msgbox "Erreur de la mise à jour de Gablue"
    exit 1
}

# Attraper les erreurs avec trap
trap 'on_error' ERR

# Mettre à jour le texte affiché
qdbus $dbusRef setLabelText "Annulation des mises à jour en attente..."
rpm-ostree cancel

# Mettre à jour le texte
qdbus $dbusRef setLabelText "Mise à jour du système via rpm-ostree..."
rpm-ostree upgrade

# Mettre à jour le texte
qdbus $dbusRef setLabelText "Mise à jour des flatpaks..."
flatpak update -y

# Fermer la barre de progression
qdbus $dbusRef close

# afficher une boîte de dialogue avec option de redémarrage
kdialog --title "Mise à jour réussie" --yesno "Gablue est à jour, un redémarrage est nécessaire pour appliquer les changements.\nVoulez-vous redémarrer maintenant ?"
if [ $? -eq 0 ]; then
    # Redémarrer si l'utilisateur clique sur "Oui"
    systemctl reboot
fi
