#!/usr/bin/bash

# Recherche et kill tous les processus windows (xbox360 inclu)
pgrep -i '(.*\.(exe|dll|msi|bat|com|lnk)$)|(.*(wine|proton).*))' |xargs -n1 kill -9
pgrep -f bottles | xargs -I {} sh -c 'ps -p {} -o comm= | grep -q "^bwrap$" && kill -9 {}'

# Recherche et kill tous les emulateurs ouverts
pgrep -f suyu |xargs -n1 kill -9
pgrep -f eden |xargs -n1 kill -9
pgrep -f sudachi |xargs -n1 kill -9
pgrep -f dolphin-emu |xargs -n1 kill -9
pgrep -f yuzu |xargs -n1 kill -9
pgrep -f citron |xargs -n1 kill -9
pgrep -f retroarch |xargs -n1 kill -9
pgrep -f xemu |xargs -n1 kill -9
pgrep -f rpcs3 |xargs -n1 kill -9
pgrep -f retroarch |xargs -n1 kill -9
pgrep -f duckstation |xargs -n1 kill -9
pgrep -f pcsx2 |xargs -n1 kill -9
pgrep -f lime3ds |xargs -n1 kill -9
pgrep -f ryujinx |xargs -n1 kill -9
pgrep -f Cemu |xargs -n1 kill -9
pgrep -f flycast |xargs -n1 kill -9
pgrep -f shadps4 |xargs -n1 kill -9
pgrep -f PokeMMO |xargs -n1 kill -9
pgrep -f PPSSPP |xargs -n1 kill -9
pkill -9 jellyfin
