#!/usr/bin/bash

# Exécuter toutes les commandes en arrière-plan en regroupant les tâches indépendantes
{
  # Recherche et kill tous les processus Windows (xbox360 inclus)
  pgrep -f -i '(.*\.(exe|bat).*|.*(wine|proton).*)' | grep -v -E "^($(pgrep -i '^(steam|steamwebhelper|steam-runtime-l)$' | paste -sd '|' -))$" | xargs kill -9 &

  # Gestion des processus bottles (spécifique avec vérification bwrap)
  pgrep -f bottles | xargs -I {} sh -c 'ps -p {} -o comm= | grep -q "^bwrap$" && kill -9 {}' &

  # Commande spécifique pour eden et citron avec fusermount
  (pgrep -f mount_eden | xargs -n1 kill -9 && sleep 1 && fusermount -u /tmp/.mount_eden*) &
  (pgrep -f mount_citro | xargs -n1 kill -9 && sleep 1 && fusermount -u /tmp/.mount_citro*) &

   # Kill des émulateurs (tous en parallèle)
  for emu in suyu sudachi dolphin-emu yuzu citron retroarch xemu rpcs3 duckstation pcsx2 lime3ds ryujinx Cemu flycast shadps4 PokeMMO PPSSPP; do
    pgrep -f "$emu" | xargs -n1 kill -9 &
  done

  # Kill des processus jellyfin et sober
  pkill -9 jellyfin &
  pkill -9 sober &
} > /dev/null 2>&1 &

# Attendre que toutes les tâches en arrière-plan soient terminées (optionnel)
wait
