#!/usr/bin/bash

# Vérifie si une instance est déjà en cours d'exécution
LOCKFILE="/tmp/launchgamepadshortcuts.lock"

# Utilise flock pour verrouiller - sort immédiatement si déjà verrouillé
exec 200>"$LOCKFILE"
if ! flock -n 200; then
    echo "Une instance est déjà en cours d'exécution"
    exit 1
fi

# Kill le process si existant
pgrep -f gamepadshortcuts.py |xargs -n1 kill -9

#Wait 2 seconds
sleep 2

# Boucle pour relancer gamepadshortcuts.py si ça se termine
while true; do
    # Lance gamepadshortcuts
    /usr/bin/python3 /usr/share/ublue-os/gablue/scripts/gamepadshortcuts/gamepadshortcuts.py
    # Attendre 1 seconde avant de relancer (optionnel)
    sleep 1
done
