#!/usr/bin/bash

# Kill le process si existant
pgrep -f gamepadshortcuts.py |xargs -n1 kill -9

#Wait 2 seconds
sleep 2

# Boucle pour relancer gamepadshortcuts.py si ça se termine
while true; do
    # Lance gamepadshortcuts
    /usr/bin/python /usr/share/ublue-os/gablue/scripts/gamepadshortcuts/gamepadshortcuts.py
    # Attendre 1 seconde avant de relancer (optionnel)
    sleep 1
done
