#!/usr/bin/bash

if rpm-ostree cancel && rpm-ostree upgrade; then
    echo 'Tout est ok!'
    for ((i=5; i>=1; i--))
    do
        echo "$i"
        sleep 1
    done
else
    echo 'Echec...'
    for ((i=5; i>=1; i--))
    do
        echo "$i"
        sleep 1
    done
fi


